name: Build and Test

on: [push, pull_request]

jobs:

  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Build package
      run: scripts/build-wheel.sh
      shell: bash

    - name: Install package
      run: pip install -U assets/dist/tflite-*.whl

    - name: Install development dependencies
      run: pip install -r requirements.txt

    - name: Testing
      run: pytest
